/// Hand-maintained type definitions for the assimp 6.0.5 C API.
///
/// assimp's public data types live in heavily-templated C++ headers
/// (aiVector3t!TReal etc.) that no regex can translate safely, so — unlike
/// `bind/core.d`, which is generated by tools/gen_binds.py — this module is
/// maintained by hand and audited field-by-field against the upstream headers
/// in `include/assimp/`. Layouts here must match the C ABI byte-for-byte.
///
/// Enum members use the bare (prefix-stripped) spelling, e.g.
/// `aiTextureType.DIFFUSE`. Bit-flag sets that C code uses unqualified
/// (the `aiProcess_*` post-processing steps) are kept as module-scope
/// manifest constants so they read exactly like the C names.
module bindbc.assimp.bind.types;

extern (C):

// ---------------------------------------------------------------------------
// defs.h — precision-dependent scalar aliases
// ---------------------------------------------------------------------------

version (ASSIMP_DOUBLE_PRECISION) {
    alias ai_real = double;
    alias ai_int  = long;
    alias ai_uint = ulong;
    enum ASSIMP_AI_REAL_TEXT_PRECISION = 16;
} else {
    alias ai_real = float;
    alias ai_int  = int;
    alias ai_uint = uint;
    enum ASSIMP_AI_REAL_TEXT_PRECISION = 8;
}

alias ai_int32  = int;    /// int32_t
alias ai_uint32 = uint;   /// uint32_t

alias aiBool = int;
enum AI_FALSE = 0;
enum AI_TRUE  = 1;

// ---------------------------------------------------------------------------
// math constants (defs.h)
// ---------------------------------------------------------------------------

enum AI_MATH_PI        = 3.141592653589793238462643383279;
enum AI_MATH_TWO_PI    = AI_MATH_PI * 2.0;
enum AI_MATH_HALF_PI   = AI_MATH_PI * 0.5;

enum AI_MATH_PI_F      = 3.1415926538f;
enum AI_MATH_TWO_PI_F  = AI_MATH_PI_F * 2.0f;
enum AI_MATH_HALF_PI_F = AI_MATH_PI_F * 0.5f;

enum ai_epsilon = cast(ai_real) 1e-6;

/// Convert between radians and degrees (mirror of the AI_DEG_TO_RAD macros).
alias AI_DEG_TO_RAD = x => x * cast(ai_real) 0.0174532925;
alias AI_RAD_TO_DEG = x => x * cast(ai_real) 57.2957795;

/// Maximum number of elements of `type` assimp will allocate in one block.
enum AI_MAX_ALLOC(type) = (256U * 1024 * 1024) / type.sizeof;

// ---------------------------------------------------------------------------
// vector2.h / vector3.h / color4.h / matrix*.h / quaternion.h
// ---------------------------------------------------------------------------

struct aiVector2D { ai_real x, y; }
struct aiVector3D { ai_real x, y, z; }

/// NOTE: colors are always plain `float`, even under ASSIMP_DOUBLE_PRECISION.
struct aiColor3D { float r, g, b; }
struct aiColor4D { float r, g, b, a; }

struct aiMatrix3x3 {
    ai_real a1, a2, a3;
    ai_real b1, b2, b3;
    ai_real c1, c2, c3;
}

struct aiMatrix4x4 {
    ai_real a1, a2, a3, a4;
    ai_real b1, b2, b3, b4;
    ai_real c1, c2, c3, c4;
    ai_real d1, d2, d3, d4;
}

/// Field order is w, x, y, z.
struct aiQuaternion { ai_real w, x, y, z; }

// ---------------------------------------------------------------------------
// types.h
// ---------------------------------------------------------------------------

enum AI_MAXLEN = 1024;

struct aiPlane { ai_real a, b, c, d; }
struct aiRay   { aiVector3D pos, dir; }

/// Fixed-capacity UTF-8 string. `length` excludes the NUL terminator.
struct aiString {
    ai_uint32 length;
    char[AI_MAXLEN] data;
}

enum aiReturn {
    SUCCESS     = 0x0,
    FAILURE     = -0x1,
    OUTOFMEMORY = -0x3,
    _ENFORCE_ENUM_SIZE = 0x7fffffff,
}
enum AI_SUCCESS     = aiReturn.SUCCESS;
enum AI_FAILURE     = aiReturn.FAILURE;
enum AI_OUTOFMEMORY = aiReturn.OUTOFMEMORY;

enum aiOrigin {
    SET = 0x0,
    CUR = 0x1,
    END = 0x2,
    _ENFORCE_ENUM_SIZE = 0x7fffffff,
}

enum aiDefaultLogStream {
    FILE     = 0x1,
    STDOUT   = 0x2,
    STDERR   = 0x4,
    DEBUGGER = 0x8,
    _ENFORCE_ENUM_SIZE = 0x7fffffff,
}
enum DLS_FILE     = aiDefaultLogStream.FILE;
enum DLS_STDOUT   = aiDefaultLogStream.STDOUT;
enum DLS_STDERR   = aiDefaultLogStream.STDERR;
enum DLS_DEBUGGER = aiDefaultLogStream.DEBUGGER;

struct aiMemoryInfo {
    uint textures;
    uint materials;
    uint meshes;
    uint nodes;
    uint animations;
    uint cameras;
    uint lights;
    uint total;
}

struct aiBuffer {
    const(char)* data;   /// begin
    const(char)* end;    /// one-past-end
}

// ---------------------------------------------------------------------------
// aabb.h
// ---------------------------------------------------------------------------

struct aiAABB {
    aiVector3D mMin;
    aiVector3D mMax;
}

// ---------------------------------------------------------------------------
// mesh.h
// ---------------------------------------------------------------------------

enum AI_MAX_FACE_INDICES            = 0x7fff;
enum AI_MAX_BONE_WEIGHTS            = 0x7fffffff;
enum AI_MAX_VERTICES                = 0x7fffffff;
enum AI_MAX_FACES                   = 0x7fffffff;
enum AI_MAX_NUMBER_OF_COLOR_SETS    = 0x8;
enum AI_MAX_NUMBER_OF_TEXTURECOORDS = 0x8;

struct aiFace {
    uint  mNumIndices;
    uint* mIndices;
}

struct aiVertexWeight {
    uint    mVertexId;
    ai_real mWeight;
}

struct aiBone {
    aiString mName;
    uint     mNumWeights;
    // Present unless assimp was built with ASSIMP_BUILD_NO_ARMATUREPOPULATE_PROCESS.
    // The default / official 6.0.5 binaries DO include these — pass
    // `-version=ASSIMP_BUILD_NO_ARMATUREPOPULATE_PROCESS` only if you link a
    // custom build that defined that macro.
    version (ASSIMP_BUILD_NO_ARMATUREPOPULATE_PROCESS) {} else {
        aiNode* mArmature;
        aiNode* mNode;
    }
    aiVertexWeight* mWeights;
    aiMatrix4x4     mOffsetMatrix;
}

enum aiPrimitiveType {
    POINT            = 0x1,
    LINE             = 0x2,
    TRIANGLE         = 0x4,
    POLYGON          = 0x8,
    NGONEncodingFlag = 0x10,
    _Force32Bit      = 0x7fffffff,
}

/// aiPrimitiveType flag for a face with `n` indices.
enum AI_PRIMITIVE_TYPE_FOR_N_INDICES(uint n) =
    (n > 3 ? aiPrimitiveType.POLYGON : cast(aiPrimitiveType)(1u << (n - 1)));

struct aiAnimMesh {
    aiString    mName;
    aiVector3D* mVertices;
    aiVector3D* mNormals;
    aiVector3D* mTangents;
    aiVector3D* mBitangents;
    aiColor4D*[AI_MAX_NUMBER_OF_COLOR_SETS]     mColors;
    aiVector3D*[AI_MAX_NUMBER_OF_TEXTURECOORDS] mTextureCoords;
    uint  mNumVertices;
    float mWeight;
}

enum aiMorphingMethod {
    UNKNOWN          = 0x0,
    VERTEX_BLEND     = 0x1,
    MORPH_NORMALIZED = 0x2,
    MORPH_RELATIVE   = 0x3,
    _Force32Bit      = 0x7fffffff,
}

struct aiMesh {
    uint        mPrimitiveTypes;
    uint        mNumVertices;
    uint        mNumFaces;
    aiVector3D* mVertices;
    aiVector3D* mNormals;
    aiVector3D* mTangents;
    aiVector3D* mBitangents;
    aiColor4D*[AI_MAX_NUMBER_OF_COLOR_SETS]     mColors;
    aiVector3D*[AI_MAX_NUMBER_OF_TEXTURECOORDS] mTextureCoords;
    uint[AI_MAX_NUMBER_OF_TEXTURECOORDS]        mNumUVComponents;
    aiFace*      mFaces;
    uint         mNumBones;
    aiBone**     mBones;
    uint         mMaterialIndex;
    aiString     mName;
    uint         mNumAnimMeshes;
    aiAnimMesh** mAnimMeshes;
    aiMorphingMethod mMethod;
    aiAABB       mAABB;
    aiString**   mTextureCoordsNames;   /// NEW in 6.0 — [AI_MAX_NUMBER_OF_TEXTURECOORDS]
}

struct aiSkeletonBone {
    int mParent;
    version (ASSIMP_BUILD_NO_ARMATUREPOPULATE_PROCESS) {} else {
        aiNode* mArmature;
        aiNode* mNode;
    }
    uint            mNumnWeights;   /// (sic — upstream spelling)
    aiMesh*         mMeshId;
    aiVertexWeight* mWeights;
    aiMatrix4x4     mOffsetMatrix;
    aiMatrix4x4     mLocalMatrix;
}

struct aiSkeleton {
    aiString          mName;
    uint              mNumBones;
    aiSkeletonBone**  mBones;
}

// ---------------------------------------------------------------------------
// anim.h
// ---------------------------------------------------------------------------

enum aiAnimInterpolation {
    Step             = 0x0,
    Linear           = 0x1,
    Spherical_Linear = 0x2,
    Cubic_Spline     = 0x3,
    _Force32Bit      = 0x7fffffff,
}

struct aiVectorKey {
    double              mTime;
    aiVector3D          mValue;
    aiAnimInterpolation mInterpolation;   /// NEW in 6.0
}

struct aiQuatKey {
    double              mTime;
    aiQuaternion        mValue;
    aiAnimInterpolation mInterpolation;   /// NEW in 6.0
}

struct aiMeshKey {
    double mTime;
    uint   mValue;
}

struct aiMeshMorphKey {
    double  mTime;
    uint*   mValues;
    double* mWeights;
    uint    mNumValuesAndWeights;
}

enum aiAnimBehaviour {
    DEFAULT     = 0x0,
    CONSTANT    = 0x1,
    LINEAR      = 0x2,
    REPEAT      = 0x3,
    _Force32Bit = 0x7fffffff,
}

struct aiNodeAnim {
    aiString     mNodeName;
    uint         mNumPositionKeys;
    aiVectorKey* mPositionKeys;
    uint         mNumRotationKeys;
    aiQuatKey*   mRotationKeys;
    uint         mNumScalingKeys;
    aiVectorKey* mScalingKeys;
    aiAnimBehaviour mPreState;
    aiAnimBehaviour mPostState;
}

struct aiMeshAnim {
    aiString   mName;
    uint       mNumKeys;
    aiMeshKey* mKeys;
}

struct aiMeshMorphAnim {
    aiString        mName;
    uint            mNumKeys;
    aiMeshMorphKey* mKeys;
}

struct aiAnimation {
    aiString     mName;
    double       mDuration;
    double       mTicksPerSecond;
    uint         mNumChannels;
    aiNodeAnim** mChannels;
    uint         mNumMeshChannels;
    aiMeshAnim** mMeshChannels;
    uint         mNumMorphMeshChannels;
    aiMeshMorphAnim** mMorphMeshChannels;
}

// ---------------------------------------------------------------------------
// camera.h
// ---------------------------------------------------------------------------

struct aiCamera {
    aiString   mName;
    aiVector3D mPosition;
    aiVector3D mUp;
    aiVector3D mLookAt;
    float mHorizontalFOV;
    float mClipPlaneNear;
    float mClipPlaneFar;
    float mAspect;
    float mOrthographicWidth;   /// NEW in 6.0
}

// ---------------------------------------------------------------------------
// light.h
// ---------------------------------------------------------------------------

enum aiLightSourceType {
    UNDEFINED   = 0x0,
    DIRECTIONAL = 0x1,
    POINT       = 0x2,
    SPOT        = 0x3,
    AMBIENT     = 0x4,
    AREA        = 0x5,
    _Force32Bit = 0x7fffffff,
}

struct aiLight {
    aiString          mName;
    aiLightSourceType mType;
    aiVector3D mPosition;
    aiVector3D mDirection;
    aiVector3D mUp;
    float mAttenuationConstant;
    float mAttenuationLinear;
    float mAttenuationQuadratic;
    aiColor3D mColorDiffuse;
    aiColor3D mColorSpecular;
    aiColor3D mColorAmbient;
    float mAngleInnerCone;
    float mAngleOuterCone;
    aiVector2D mSize;
}

// ---------------------------------------------------------------------------
// texture.h
// ---------------------------------------------------------------------------

enum AI_EMBEDDED_TEXNAME_PREFIX = "*";
enum HINTMAXTEXTURELEN = 9;

align(1) struct aiTexel {
    ubyte b, g, r, a;
}

struct aiTexture {
    uint mWidth;
    uint mHeight;
    char[HINTMAXTEXTURELEN] achFormatHint;   /// 8 chars + NUL terminator
    aiTexel* pcData;
    aiString mFilename;
}

// ---------------------------------------------------------------------------
// metadata.h
// ---------------------------------------------------------------------------

enum aiMetadataType {
    BOOL       = 0,
    INT32      = 1,
    UINT64     = 2,
    FLOAT      = 3,
    DOUBLE     = 4,
    AISTRING   = 5,
    AIVECTOR3D = 6,
    AIMETADATA = 7,   /// NEW in 6.0 — nested aiMetadata
    INT64      = 8,   /// NEW in 6.0
    UINT32     = 9,   /// NEW in 6.0
    META_MAX   = 10,
    FORCE_32BIT = 0x7fffffff,
}

struct aiMetadataEntry {
    aiMetadataType mType;
    void* mData;
}

struct aiMetadata {
    uint mNumProperties;
    aiString* mKeys;
    aiMetadataEntry* mValues;
}

// ---------------------------------------------------------------------------
// material.h — enums
// ---------------------------------------------------------------------------

enum AI_DEFAULT_MATERIAL_NAME = "DefaultMaterial";

enum aiTextureOp {
    Multiply    = 0x0,
    Add         = 0x1,
    Subtract    = 0x2,
    Divide      = 0x3,
    SmoothAdd   = 0x4,
    SignedAdd   = 0x5,
    _Force32Bit = 0x7fffffff,
}

enum aiTextureMapMode {
    Wrap        = 0x0,
    Clamp       = 0x1,
    Decal       = 0x3,
    Mirror      = 0x2,
    _Force32Bit = 0x7fffffff,
}

enum aiTextureMapping {
    UV          = 0x0,
    SPHERE      = 0x1,
    CYLINDER    = 0x2,
    BOX         = 0x3,
    PLANE       = 0x4,
    OTHER       = 0x5,
    _Force32Bit = 0x7fffffff,
}

enum aiTextureType {
    NONE                    = 0,
    DIFFUSE                 = 1,
    SPECULAR                = 2,
    AMBIENT                 = 3,
    EMISSIVE                = 4,
    HEIGHT                  = 5,
    NORMALS                 = 6,
    SHININESS               = 7,
    OPACITY                 = 8,
    DISPLACEMENT            = 9,
    LIGHTMAP                = 10,
    REFLECTION              = 11,
    BASE_COLOR              = 12,
    NORMAL_CAMERA           = 13,
    EMISSION_COLOR          = 14,
    METALNESS               = 15,
    DIFFUSE_ROUGHNESS       = 16,
    AMBIENT_OCCLUSION       = 17,
    UNKNOWN                 = 18,
    SHEEN                   = 19,
    CLEARCOAT               = 20,
    TRANSMISSION            = 21,
    MAYA_BASE               = 22,
    MAYA_SPECULAR           = 23,
    MAYA_SPECULAR_COLOR     = 24,
    MAYA_SPECULAR_ROUGHNESS = 25,
    ANISOTROPY              = 26,
    GLTF_METALLIC_ROUGHNESS = 27,
    _Force32Bit             = 0x7fffffff,
}
enum AI_TEXTURE_TYPE_MAX = aiTextureType.GLTF_METALLIC_ROUGHNESS;

enum aiShadingMode {
    Flat         = 0x1,
    Gouraud      = 0x2,
    Phong        = 0x3,
    Blinn        = 0x4,
    Toon         = 0x5,
    OrenNayar    = 0x6,
    Minnaert     = 0x7,
    CookTorrance = 0x8,
    NoShading    = 0x9,
    Unlit        = NoShading,
    Fresnel      = 0xa,
    PBR_BRDF     = 0xb,
    _Force32Bit  = 0x7fffffff,
}

enum aiTextureFlags {
    Invert      = 0x1,
    UseAlpha    = 0x2,
    IgnoreAlpha = 0x4,
    _Force32Bit = 0x7fffffff,
}

enum aiBlendMode {
    Default     = 0x0,
    Additive    = 0x1,
    _Force32Bit = 0x7fffffff,
}

enum aiPropertyTypeInfo {
    Float       = 0x1,
    Double      = 0x2,
    String      = 0x3,
    Integer     = 0x4,
    Buffer      = 0x5,
    _Force32Bit = 0x7fffffff,
}

/// Packed (pushpack1 in the C header).
align(1) struct aiUVTransform {
    aiVector2D mTranslation;
    aiVector2D mScaling;
    ai_real    mRotation;
}

struct aiMaterialProperty {
    aiString           mKey;
    uint               mSemantic;
    uint               mIndex;
    uint               mDataLength;
    aiPropertyTypeInfo mType;
    char*              mData;
}

struct aiMaterial {
    aiMaterialProperty** mProperties;
    uint                 mNumProperties;
    uint                 mNumAllocated;
}

// ---------------------------------------------------------------------------
// material.h — property keys
//
// An assimp material key is the triple (name, semantic, index). Non-texture
// keys hardcode semantic = index = 0. Texture-bound keys vary the texture
// type (semantic) and slot index, so they are exposed as the
// `AI_MATKEY_TEXTURE!(type, N)`-style templates below.
// ---------------------------------------------------------------------------

struct AiMatKey {
    const(char)* key;
    uint semantic;
    uint index;
}

// standard keys
enum AI_MATKEY_NAME                    = AiMatKey("?mat.name", 0, 0);
enum AI_MATKEY_TWOSIDED                = AiMatKey("$mat.twosided", 0, 0);
enum AI_MATKEY_SHADING_MODEL           = AiMatKey("$mat.shadingm", 0, 0);
enum AI_MATKEY_ENABLE_WIREFRAME        = AiMatKey("$mat.wireframe", 0, 0);
enum AI_MATKEY_BLEND_FUNC              = AiMatKey("$mat.blend", 0, 0);
enum AI_MATKEY_OPACITY                 = AiMatKey("$mat.opacity", 0, 0);
enum AI_MATKEY_TRANSPARENCYFACTOR      = AiMatKey("$mat.transparencyfactor", 0, 0);
enum AI_MATKEY_BUMPSCALING             = AiMatKey("$mat.bumpscaling", 0, 0);
enum AI_MATKEY_SHININESS               = AiMatKey("$mat.shininess", 0, 0);
enum AI_MATKEY_REFLECTIVITY            = AiMatKey("$mat.reflectivity", 0, 0);
enum AI_MATKEY_SHININESS_STRENGTH      = AiMatKey("$mat.shinpercent", 0, 0);
enum AI_MATKEY_REFRACTI                = AiMatKey("$mat.refracti", 0, 0);
enum AI_MATKEY_COLOR_DIFFUSE           = AiMatKey("$clr.diffuse", 0, 0);
enum AI_MATKEY_COLOR_AMBIENT           = AiMatKey("$clr.ambient", 0, 0);
enum AI_MATKEY_COLOR_SPECULAR          = AiMatKey("$clr.specular", 0, 0);
enum AI_MATKEY_COLOR_EMISSIVE          = AiMatKey("$clr.emissive", 0, 0);
enum AI_MATKEY_COLOR_TRANSPARENT       = AiMatKey("$clr.transparent", 0, 0);
enum AI_MATKEY_COLOR_REFLECTIVE        = AiMatKey("$clr.reflective", 0, 0);
enum AI_MATKEY_GLOBAL_BACKGROUND_IMAGE = AiMatKey("?bg.global", 0, 0);
enum AI_MATKEY_GLOBAL_SHADERLANG       = AiMatKey("?sh.lang", 0, 0);
enum AI_MATKEY_SHADER_VERTEX           = AiMatKey("?sh.vs", 0, 0);
enum AI_MATKEY_SHADER_FRAGMENT         = AiMatKey("?sh.fs", 0, 0);
enum AI_MATKEY_SHADER_GEO              = AiMatKey("?sh.gs", 0, 0);
enum AI_MATKEY_SHADER_TESSELATION      = AiMatKey("?sh.ts", 0, 0);
enum AI_MATKEY_SHADER_PRIMITIVE        = AiMatKey("?sh.ps", 0, 0);
enum AI_MATKEY_SHADER_COMPUTE          = AiMatKey("?sh.cs", 0, 0);

// PBR keys (new since assimp 5.x)
enum AI_MATKEY_USE_COLOR_MAP               = AiMatKey("$mat.useColorMap", 0, 0);
enum AI_MATKEY_BASE_COLOR                  = AiMatKey("$clr.base", 0, 0);
enum AI_MATKEY_USE_METALLIC_MAP            = AiMatKey("$mat.useMetallicMap", 0, 0);
enum AI_MATKEY_METALLIC_FACTOR             = AiMatKey("$mat.metallicFactor", 0, 0);
enum AI_MATKEY_USE_ROUGHNESS_MAP           = AiMatKey("$mat.useRoughnessMap", 0, 0);
enum AI_MATKEY_ROUGHNESS_FACTOR            = AiMatKey("$mat.roughnessFactor", 0, 0);
enum AI_MATKEY_ANISOTROPY_FACTOR           = AiMatKey("$mat.anisotropyFactor", 0, 0);
enum AI_MATKEY_SPECULAR_FACTOR             = AiMatKey("$mat.specularFactor", 0, 0);
enum AI_MATKEY_GLOSSINESS_FACTOR           = AiMatKey("$mat.glossinessFactor", 0, 0);
enum AI_MATKEY_SHEEN_COLOR_FACTOR          = AiMatKey("$clr.sheen.factor", 0, 0);
enum AI_MATKEY_SHEEN_ROUGHNESS_FACTOR      = AiMatKey("$mat.sheen.roughnessFactor", 0, 0);
enum AI_MATKEY_CLEARCOAT_FACTOR            = AiMatKey("$mat.clearcoat.factor", 0, 0);
enum AI_MATKEY_CLEARCOAT_ROUGHNESS_FACTOR  = AiMatKey("$mat.clearcoat.roughnessFactor", 0, 0);
enum AI_MATKEY_TRANSMISSION_FACTOR         = AiMatKey("$mat.transmission.factor", 0, 0);
enum AI_MATKEY_VOLUME_THICKNESS_FACTOR     = AiMatKey("$mat.volume.thicknessFactor", 0, 0);
enum AI_MATKEY_VOLUME_ATTENUATION_DISTANCE = AiMatKey("$mat.volume.attenuationDistance", 0, 0);
enum AI_MATKEY_VOLUME_ATTENUATION_COLOR    = AiMatKey("$mat.volume.attenuationColor", 0, 0);
enum AI_MATKEY_USE_EMISSIVE_MAP            = AiMatKey("$mat.useEmissiveMap", 0, 0);
enum AI_MATKEY_EMISSIVE_INTENSITY          = AiMatKey("$mat.emissiveIntensity", 0, 0);
enum AI_MATKEY_USE_AO_MAP                  = AiMatKey("$mat.useAOMap", 0, 0);
enum AI_MATKEY_ANISOTROPY_ROTATION         = AiMatKey("$mat.anisotropyRotation", 0, 0);

// texture-key base names
enum _AI_MATKEY_TEXTURE_BASE       = "$tex.file";
enum _AI_MATKEY_UVWSRC_BASE        = "$tex.uvwsrc";
enum _AI_MATKEY_TEXOP_BASE         = "$tex.op";
enum _AI_MATKEY_MAPPING_BASE       = "$tex.mapping";
enum _AI_MATKEY_TEXBLEND_BASE      = "$tex.blend";
enum _AI_MATKEY_MAPPINGMODE_U_BASE = "$tex.mapmodeu";
enum _AI_MATKEY_MAPPINGMODE_V_BASE = "$tex.mapmodev";
enum _AI_MATKEY_TEXMAP_AXIS_BASE   = "$tex.mapaxis";
enum _AI_MATKEY_UVTRANSFORM_BASE   = "$tex.uvtrafo";
enum _AI_MATKEY_TEXFLAGS_BASE      = "$tex.flags";

/// Texture-bound key families. Usage: `AI_MATKEY_TEXTURE!(aiTextureType.DIFFUSE, 0)`.
template AI_MATKEY_TEXTURE(aiTextureType type, uint N)       { enum AI_MATKEY_TEXTURE       = AiMatKey(_AI_MATKEY_TEXTURE_BASE.ptr, type, N); }
template AI_MATKEY_UVWSRC(aiTextureType type, uint N)        { enum AI_MATKEY_UVWSRC        = AiMatKey(_AI_MATKEY_UVWSRC_BASE.ptr, type, N); }
template AI_MATKEY_TEXOP(aiTextureType type, uint N)         { enum AI_MATKEY_TEXOP         = AiMatKey(_AI_MATKEY_TEXOP_BASE.ptr, type, N); }
template AI_MATKEY_MAPPING(aiTextureType type, uint N)       { enum AI_MATKEY_MAPPING       = AiMatKey(_AI_MATKEY_MAPPING_BASE.ptr, type, N); }
template AI_MATKEY_TEXBLEND(aiTextureType type, uint N)      { enum AI_MATKEY_TEXBLEND      = AiMatKey(_AI_MATKEY_TEXBLEND_BASE.ptr, type, N); }
template AI_MATKEY_MAPPINGMODE_U(aiTextureType type, uint N) { enum AI_MATKEY_MAPPINGMODE_U = AiMatKey(_AI_MATKEY_MAPPINGMODE_U_BASE.ptr, type, N); }
template AI_MATKEY_MAPPINGMODE_V(aiTextureType type, uint N) { enum AI_MATKEY_MAPPINGMODE_V = AiMatKey(_AI_MATKEY_MAPPINGMODE_V_BASE.ptr, type, N); }
template AI_MATKEY_TEXMAP_AXIS(aiTextureType type, uint N)   { enum AI_MATKEY_TEXMAP_AXIS   = AiMatKey(_AI_MATKEY_TEXMAP_AXIS_BASE.ptr, type, N); }
template AI_MATKEY_UVTRANSFORM(aiTextureType type, uint N)   { enum AI_MATKEY_UVTRANSFORM   = AiMatKey(_AI_MATKEY_UVTRANSFORM_BASE.ptr, type, N); }
template AI_MATKEY_TEXFLAGS(aiTextureType type, uint N)      { enum AI_MATKEY_TEXFLAGS      = AiMatKey(_AI_MATKEY_TEXFLAGS_BASE.ptr, type, N); }

// PBR texture-bound keys (fixed type + slot)
enum AI_MATKEY_BASE_COLOR_TEXTURE          = AiMatKey(_AI_MATKEY_TEXTURE_BASE.ptr, aiTextureType.BASE_COLOR, 0);
enum AI_MATKEY_METALLIC_TEXTURE            = AiMatKey(_AI_MATKEY_TEXTURE_BASE.ptr, aiTextureType.METALNESS, 0);
enum AI_MATKEY_ROUGHNESS_TEXTURE           = AiMatKey(_AI_MATKEY_TEXTURE_BASE.ptr, aiTextureType.DIFFUSE_ROUGHNESS, 0);
enum AI_MATKEY_SHEEN_COLOR_TEXTURE         = AiMatKey(_AI_MATKEY_TEXTURE_BASE.ptr, aiTextureType.SHEEN, 0);
enum AI_MATKEY_SHEEN_ROUGHNESS_TEXTURE     = AiMatKey(_AI_MATKEY_TEXTURE_BASE.ptr, aiTextureType.SHEEN, 1);
enum AI_MATKEY_CLEARCOAT_TEXTURE           = AiMatKey(_AI_MATKEY_TEXTURE_BASE.ptr, aiTextureType.CLEARCOAT, 0);
enum AI_MATKEY_CLEARCOAT_ROUGHNESS_TEXTURE = AiMatKey(_AI_MATKEY_TEXTURE_BASE.ptr, aiTextureType.CLEARCOAT, 1);
enum AI_MATKEY_CLEARCOAT_NORMAL_TEXTURE    = AiMatKey(_AI_MATKEY_TEXTURE_BASE.ptr, aiTextureType.CLEARCOAT, 2);
enum AI_MATKEY_TRANSMISSION_TEXTURE        = AiMatKey(_AI_MATKEY_TEXTURE_BASE.ptr, aiTextureType.TRANSMISSION, 0);
enum AI_MATKEY_VOLUME_THICKNESS_TEXTURE    = AiMatKey(_AI_MATKEY_TEXTURE_BASE.ptr, aiTextureType.TRANSMISSION, 1);
enum AI_MATKEY_ANISOTROPY_TEXTURE          = AiMatKey(_AI_MATKEY_TEXTURE_BASE.ptr, aiTextureType.ANISOTROPY, 0);

// ---------------------------------------------------------------------------
// scene.h
// ---------------------------------------------------------------------------

struct aiNode {
    aiString    mName;
    aiMatrix4x4 mTransformation;
    aiNode*     mParent;
    uint        mNumChildren;
    aiNode**    mChildren;
    uint        mNumMeshes;
    uint*       mMeshes;
    aiMetadata* mMetaData;
}

enum AI_SCENE_FLAGS_INCOMPLETE         = 0x1;
enum AI_SCENE_FLAGS_VALIDATED          = 0x2;
enum AI_SCENE_FLAGS_VALIDATION_WARNING = 0x4;
enum AI_SCENE_FLAGS_NON_VERBOSE_FORMAT = 0x8;
enum AI_SCENE_FLAGS_TERRAIN            = 0x10;
enum AI_SCENE_FLAGS_ALLOW_SHARED       = 0x20;

struct aiScene {
    uint          mFlags;
    aiNode*       mRootNode;
    uint          mNumMeshes;
    aiMesh**      mMeshes;
    uint          mNumMaterials;
    aiMaterial**  mMaterials;
    uint          mNumAnimations;
    aiAnimation** mAnimations;
    uint          mNumTextures;
    aiTexture**   mTextures;
    uint          mNumLights;
    aiLight**     mLights;
    uint          mNumCameras;
    aiCamera**    mCameras;
    aiMetadata*   mMetaData;
    aiString      mName;          /// NEW in 6.0
    uint          mNumSkeletons;  /// NEW in 6.0
    aiSkeleton**  mSkeletons;     /// NEW in 6.0
    char*         mPrivate;
}

// ---------------------------------------------------------------------------
// postprocess.h — post-processing flags (kept unqualified, as in C)
// ---------------------------------------------------------------------------

enum : uint {
    aiProcess_CalcTangentSpace         = 0x1,
    aiProcess_JoinIdenticalVertices    = 0x2,
    aiProcess_MakeLeftHanded           = 0x4,
    aiProcess_Triangulate              = 0x8,
    aiProcess_RemoveComponent          = 0x10,
    aiProcess_GenNormals               = 0x20,
    aiProcess_GenSmoothNormals         = 0x40,
    aiProcess_SplitLargeMeshes         = 0x80,
    aiProcess_PreTransformVertices     = 0x100,
    aiProcess_LimitBoneWeights         = 0x200,
    aiProcess_ValidateDataStructure    = 0x400,
    aiProcess_ImproveCacheLocality     = 0x800,
    aiProcess_RemoveRedundantMaterials = 0x1000,
    aiProcess_FixInfacingNormals       = 0x2000,
    aiProcess_PopulateArmatureData     = 0x4000,
    aiProcess_SortByPType              = 0x8000,
    aiProcess_FindDegenerates          = 0x10000,
    aiProcess_FindInvalidData          = 0x20000,
    aiProcess_GenUVCoords              = 0x40000,
    aiProcess_TransformUVCoords        = 0x80000,
    aiProcess_FindInstances            = 0x100000,
    aiProcess_OptimizeMeshes           = 0x200000,
    aiProcess_OptimizeGraph            = 0x400000,
    aiProcess_FlipUVs                  = 0x800000,
    aiProcess_FlipWindingOrder         = 0x1000000,
    aiProcess_SplitByBoneCount         = 0x2000000,
    aiProcess_Debone                   = 0x4000000,
    aiProcess_GlobalScale              = 0x8000000,
    aiProcess_EmbedTextures            = 0x10000000,
    aiProcess_ForceGenNormals          = 0x20000000,
    aiProcess_DropNormals              = 0x40000000,
    aiProcess_GenBoundingBoxes         = 0x80000000,
}

enum uint aiProcess_ConvertToLeftHanded =
    aiProcess_MakeLeftHanded | aiProcess_FlipUVs | aiProcess_FlipWindingOrder;

enum uint aiProcessPreset_TargetRealtime_Fast =
    aiProcess_CalcTangentSpace | aiProcess_GenNormals | aiProcess_JoinIdenticalVertices |
    aiProcess_Triangulate | aiProcess_GenUVCoords | aiProcess_SortByPType;

enum uint aiProcessPreset_TargetRealtime_Quality =
    aiProcess_CalcTangentSpace | aiProcess_GenSmoothNormals | aiProcess_JoinIdenticalVertices |
    aiProcess_ImproveCacheLocality | aiProcess_LimitBoneWeights | aiProcess_RemoveRedundantMaterials |
    aiProcess_SplitLargeMeshes | aiProcess_Triangulate | aiProcess_GenUVCoords |
    aiProcess_SortByPType | aiProcess_FindDegenerates | aiProcess_FindInvalidData;

enum uint aiProcessPreset_TargetRealtime_MaxQuality =
    aiProcessPreset_TargetRealtime_Quality | aiProcess_FindInstances |
    aiProcess_ValidateDataStructure | aiProcess_OptimizeMeshes;

// ---------------------------------------------------------------------------
// importerdesc.h
// ---------------------------------------------------------------------------

enum aiImporterFlags {
    SupportTextFlavour       = 0x1,
    SupportBinaryFlavour     = 0x2,
    SupportCompressedFlavour = 0x4,
    LimitedSupport           = 0x8,
    Experimental             = 0x10,
}

struct aiImporterDesc {
    const(char)* mName;
    const(char)* mAuthor;
    const(char)* mMaintainer;
    const(char)* mComments;
    uint mFlags;
    uint mMinMajor;
    uint mMinMinor;
    uint mMaxMajor;
    uint mMaxMinor;
    const(char)* mFileExtensions;
}

// ---------------------------------------------------------------------------
// cfileio.h — I/O callbacks
// ---------------------------------------------------------------------------

alias aiFileWriteProc = size_t   function(aiFile*, const(char)*, size_t, size_t);
alias aiFileReadProc  = size_t   function(aiFile*, char*, size_t, size_t);
alias aiFileTellProc  = size_t   function(aiFile*);
alias aiFileFlushProc = void     function(aiFile*);
alias aiFileSeek      = aiReturn function(aiFile*, size_t, aiOrigin);
alias aiFileOpenProc  = aiFile*  function(aiFileIO*, const(char)*, const(char)*);
alias aiFileCloseProc = void     function(aiFileIO*, aiFile*);
alias aiUserData      = char*;

struct aiFileIO {
    aiFileOpenProc  OpenProc;
    aiFileCloseProc CloseProc;
    aiUserData      UserData;
}

struct aiFile {
    aiFileReadProc  ReadProc;
    aiFileWriteProc WriteProc;
    aiFileTellProc  TellProc;
    aiFileTellProc  FileSizeProc;
    aiFileSeek      SeekProc;
    aiFileFlushProc FlushProc;
    aiUserData      UserData;
}

// ---------------------------------------------------------------------------
// cimport.h — logging + property store
// ---------------------------------------------------------------------------

alias aiLogStreamCallback = void function(const(char)* message, char* user);

struct aiLogStream {
    aiLogStreamCallback callback;
    char* user;
}

/// Opaque import-property container (cimport.h).
struct aiPropertyStore {
    char sentinel;
}

// ---------------------------------------------------------------------------
// cexport.h
// ---------------------------------------------------------------------------

struct aiExportFormatDesc {
    const(char)* id;
    const(char)* description;
    const(char)* fileExtension;
}

struct aiExportDataBlob {
    size_t size;
    void*  data;
    aiString name;
    aiExportDataBlob* next;
}

// ---------------------------------------------------------------------------
// version.h — aiGetCompileFlags() bits
// ---------------------------------------------------------------------------

enum ASSIMP_CFLAGS_SHARED         = 0x1;
enum ASSIMP_CFLAGS_STLPORT        = 0x2;
enum ASSIMP_CFLAGS_DEBUG          = 0x4;
enum ASSIMP_CFLAGS_NOBOOST        = 0x8;
enum ASSIMP_CFLAGS_SINGLETHREADED = 0x10;
enum ASSIMP_CFLAGS_DOUBLE_SUPPORT = 0x20;
