#!/usr/bin/env python3
"""
Regenerates D-Assimp function bindings (source/bindbc/assimp/bind/core.d)
from the upstream assimp C-API headers.

assimp's data types live in heavily-templated C++ headers (aiVector3t<TReal>
etc.) that no regex can translate safely, so `bind/types.d` is maintained by
hand. Only the flat `extern "C"` function surface is generated here.

It scans the headers that actually expose C entry points:
    cimport.h  cexport.h  version.h  importerdesc.h  material.h
and emits one FnBind{} row per `ASSIMP_API <ret> aiXxx(<args>);` declaration
(consumed by the joinFnBinds mixin from bindbc-common).

Run from the repo root after updating the submodule:
    python3 tools/gen_binds.py extern/assimp/include/assimp
"""

import argparse
import pathlib
import re
import sys
from textwrap import dedent

# Headers that contain the C API. Other ASSIMP_API occurrences live on C++
# class methods (BaseImporter, Exporter, ...) and are intentionally skipped.
C_API_HEADERS = [
    'cimport.h', 'cexport.h', 'version.h', 'importerdesc.h', 'material.h',
]

# Symbols that look like C functions but are AI_FORCE_INLINE wrappers in the
# .inl files (no exported symbol) — provided by hand in package.d instead.
SKIP_SYMBOLS = {'aiGetMaterialFloat', 'aiGetMaterialInteger'}

# D keywords that can appear as C parameter names and must be renamed.
D_KEYWORDS = {
    'in', 'out', 'ref', 'function', 'delegate', 'body', 'scope', 'align',
    'module', 'version', 'debug', 'override', 'is', 'in_', 'cast', 'alias',
    'mixin', 'with', 'lazy', 'shared', 'immutable', 'const', 'inout',
}

# A declaration starts at column 0 with ASSIMP_API and runs to the first ';'.
DECL_START = re.compile(r'^ASSIMP_API\b')


def gather_decls(text: str):
    """Yield whole `ASSIMP_API ... ;` declarations, joined across lines."""
    lines = text.splitlines()
    i = 0
    while i < len(lines):
        if DECL_START.match(lines[i]):
            buf = [lines[i]]
            while ';' not in buf[-1] and i + 1 < len(lines):
                i += 1
                buf.append(lines[i])
            yield ' '.join(s.strip() for s in buf)
        i += 1


# Matches: ASSIMP_API <return-type-with-stars> <aiName> ( <params> ) ;
# `ret` keeps any trailing `*` so const-correctness survives the C->D mapping.
DECL_RE = re.compile(
    r'^ASSIMP_API\s+(?P<ret>.+?[\s\*])(?P<name>ai[A-Za-z0-9_]+)\s*\((?P<params>.*)\)\s*;\s*$'
)


def c2d_type(s: str) -> str:
    s = s.strip()
    s = re.sub(r'\s+', ' ', s)
    # strip C-only decorations that carry no meaning in D
    s = re.sub(r'\bC_STRUCT\b', '', s)
    s = re.sub(r'\bC_ENUM\b', '', s)
    s = re.sub(r'\bstruct\b', '', s)
    s = re.sub(r'\benum\b', '', s)
    # primitive C spellings -> D
    s = re.sub(r'\bunsigned int\b', 'uint', s)
    s = re.sub(r'\bunsigned char\b', 'ubyte', s)
    s = re.sub(r'\bunsigned\b', 'uint', s)
    # `const TYPE *` / `TYPE const *` -> `const(TYPE)*`
    s = re.sub(r'\bconst\s+([A-Za-z_][A-Za-z_0-9]*)\s*\*', r'const(\1)*', s)
    s = re.sub(r'\b([A-Za-z_][A-Za-z_0-9]*)\s+const\s*\*', r'const(\1)*', s)
    # collapse spaces before *
    s = re.sub(r'\s*\*', '*', s)
    # leftover value-level const has no ABI effect — drop it (but not const( )
    s = re.sub(r'\bconst\b(?!\s*\()', '', s)
    s = re.sub(r'\s+', ' ', s).strip()
    return s


def sanitize_name(nm: str) -> str:
    return nm + '_' if nm in D_KEYWORDS else nm


def c2d_params(params: str) -> str:
    params = params.strip()
    if params in ('', 'void'):
        return ''
    out = []
    for p in params.split(','):
        p = p.strip()
        if not p:
            continue
        # drop C++ default-argument values (`= NULL`, `= 0`, ...)
        p = re.sub(r'\s*=\s*[^,]+$', '', p).strip()
        # pull the trailing identifier as the parameter name
        m = re.match(r'^(?P<type>.*?[\s\*])(?P<name>[A-Za-z_][A-Za-z_0-9]*)$', p)
        if not m:
            out.append(c2d_type(p))
            continue
        ty = c2d_type(m.group('type'))
        nm = sanitize_name(m.group('name'))
        out.append(f'{ty} {nm}')
    return ', '.join(out)


def parse(text: str):
    funcs = []
    for decl in gather_decls(text):
        m = DECL_RE.match(decl)
        if not m:
            continue
        name = m.group('name')
        if name in SKIP_SYMBOLS:
            continue
        ret = c2d_type(m.group('ret'))
        funcs.append((ret, name, c2d_params(m.group('params'))))
    return funcs


CORE_HEADER = dedent('''\
    /// Auto-generated by tools/gen_binds.py from the assimp C-API headers.
    /// Do not edit by hand — re-run the generator after updating the submodule.
    module bindbc.assimp.bind.core;

    import bindbc.assimp.bind.types;
    import bindbc.assimp.codegen;

    mixin(joinFnBinds((){
        FnBind[] ret = [
''')

CORE_FOOTER = dedent('''\
        ];
        return ret;
    }()));
''')


def render(funcs):
    rows = []
    for ret, name, params in funcs:
        rows.append('    {q{' + ret + '}, q{' + name + '}, q{' + params + '}},')
    return '\n'.join(rows)


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument('incdir', type=pathlib.Path,
                    help='path to .../include/assimp')
    ap.add_argument('--out', type=pathlib.Path,
                    default=pathlib.Path(__file__).resolve().parent.parent
                                                 / 'source' / 'bindbc' / 'assimp' / 'bind' / 'core.d')
    args = ap.parse_args()

    all_funcs = []
    seen = set()
    for hdr in C_API_HEADERS:
        path = args.incdir / hdr
        if not path.exists():
            print(f'warning: {path} not found, skipping', file=sys.stderr)
            continue
        for ret, name, params in parse(path.read_text()):
            if name in seen:
                continue
            seen.add(name)
            all_funcs.append((ret, name, params))

    args.out.parent.mkdir(parents=True, exist_ok=True)
    args.out.write_text(CORE_HEADER + render(all_funcs) + '\n' + CORE_FOOTER)

    print(f'functions: {len(all_funcs)}')
    print(f'wrote: {args.out}')


if __name__ == '__main__':
    sys.exit(main())
